apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
spec:
  destination:
    namespace: webapp
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 'webapp'
    repoURL: https://github.com/Prashantd3dha/ArgoCD-POC
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true